language: ruby
cache: bundler
sudo: false
rvm: 2.3.3

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_script: chmod ugo+x scripts/cibuild
script: "./scripts/cibuild"

branches:
  only:
    - master

git:
  depth: 10
